#!/usr/bin/env bash
# Verification for T037 (supervisor-owned; workers never edit it). Exit 0 = pass.
. "$(dirname "$0")/_lib.sh"
expect_ok "source fonts present (public-domain misc-fixed)" <<'CMD'
for f in 4x6 6x10 7x14 9x18; do
  test -r "/usr/share/fonts/X11/misc/$f-ISO8859-1.pcf.gz" || { echo "missing font $f"; exit 1; }
done
CMD
expect_ok "check command" 900 <<'CMD'
check
CMD
expect_ok "TestGlyphTables passes" <<'CMD'
passes TestGlyphTables internal/tui/glyph
CMD
expect_ok "data.go is byte-identical to a fresh generator run" <<'CMD'
T="$(mktemp -d)"; trap 'rm -rf "$T"' EXIT
cd internal/tui/glyph && go run gen.go -o "$T/data.go" && cmp "$T/data.go" data.go
CMD
expect_ok "generated header, ignore tag and API" <<'CMD'
head -1 internal/tui/glyph/data.go | grep -qxF '// Code generated by gen.go from the public-domain X11 misc-fixed fonts; DO NOT EDIT.' &&
head -1 internal/tui/glyph/gen.go | grep -qxF '//go:build ignore' &&
grep -qF 'Share and enjoy.' internal/tui/glyph/data.go || exit 1
d="$(go doc -all ./internal/tui/glyph)" || exit 1
for s in 'func Rows\(size int\) int' 'func Width\(size int\) int' 'func Has\(r rune\) bool' \
  'func Block\(r rune, size int\) \(rows \[\]string, ok bool\)'; do
  printf '%s\n' "$d" | grep -qE "$s" || { echo "missing: $s"; exit 1; }
done
CMD
expect_fail "negative: generator succeeds without fonts" <<'CMD'
T="$(mktemp -d)"; trap 'rm -rf "$T"' EXIT
cd internal/tui/glyph && go run gen.go -fontdir "$T/nonexistent" -o "$T/x.go"
CMD
expect_fail "negative: internal/tui/glyph imports a non-standard package" <<'CMD'
out="$(go list -deps -f '{{if not .Standard}}{{.ImportPath}}{{end}}' ./internal/tui/glyph)" || exit 0
printf '%s\n' "$out" | grep -v -x 'github.com/0x6c6d/fastread/internal/tui/glyph' | grep -q .
CMD
expect_fail "negative: a glyph test reads the system font files" <<'CMD'
grep -n -e '/usr/share/fonts' -e 'os.Open' -e 'os.ReadFile' internal/tui/glyph/*_test.go
CMD
finish
