#!/usr/bin/env bash
# Verification for T066 (supervisor-owned; workers never edit it). Exit 0 = pass.
. "$(dirname "$0")/_lib.sh"
expect_ok "third_party/gofont/LICENSE is the pinned x/image v0.36.0 Go fonts licence, byte for byte" <<'CMD'
test "$(go list -m -f '{{.Version}}' golang.org/x/image)" = v0.36.0 || { echo "go.mod does not pin golang.org/x/image v0.36.0"; exit 1; }
d="$(go list -m -f '{{.Dir}}' golang.org/x/image)" && test -n "$d" || exit 1
src="$d/font/gofont/ttfs/README"
test -s "$src" || { echo "missing $src"; exit 1; }
cmp "$src" third_party/gofont/LICENSE &&
grep -qF 'Bigelow & Holmes' third_party/gofont/LICENSE &&
grep -qF 'Redistribution and use in source and binary forms' third_party/gofont/LICENSE &&
test -w third_party/gofont/LICENSE
CMD
expect_ok "third_party/misc-fixed/LICENSE matches the fixed text byte for byte" <<'CMD'
exp="$(mktemp)"; trap 'rm -f "$exp"' EXIT
cat >"$exp" <<'EOF'
X11 misc-fixed bitmap fonts (X.Org font-misc-misc)
==================================================

fastread's TUI block glyphs for sizes 2-5 (package internal/tui/glyph, file data.go) are
generated by internal/tui/glyph/gen.go from these public-domain fonts, as installed by the
Debian package xfonts-base under /usr/share/fonts/X11/misc/:

  size 2  4x6-ISO8859-1.pcf.gz   COPYRIGHT "Public domain font.  Share and enjoy."
  size 3  6x10-ISO8859-1.pcf.gz  COPYRIGHT "Public domain terminal emulator font.  Share and enjoy."
  size 4  7x14-ISO8859-1.pcf.gz  COPYRIGHT "Public domain font.  Share and enjoy."
  size 5  9x18-ISO8859-1.pcf.gz  COPYRIGHT "Public domain font.  Share and enjoy."

Upstream: https://xorg.freedesktop.org/releases/individual/font/ (font-misc-misc).

font-misc-misc/COPYING:

    Public domain font.  Share and enjoy.
EOF
diff "$exp" third_party/misc-fixed/LICENSE
CMD
expect_ok "each installed PCF master's COPYRIGHT property appears verbatim in the notice" <<'CMD'
for f in 4x6 6x10 7x14 9x18; do
  p="/usr/share/fonts/X11/misc/$f-ISO8859-1.pcf.gz"
  test -r "$p" || { echo "missing $p"; exit 1; }
  c="$(zcat "$p" | strings | grep -m1 '^Public domain')"
  test -n "$c" || { echo "no COPYRIGHT notice in $p"; exit 1; }
  grep -qF -- "$f-ISO8859-1.pcf.gz" third_party/misc-fixed/LICENSE &&
  grep -F -- "$f-ISO8859-1.pcf.gz" third_party/misc-fixed/LICENSE | grep -qF -- "\"$c\"" || { echo "$f: notice '$c' not on its line"; exit 1; }
done
CMD
expect_ok "root LICENSE still passes its own check; Plan D14 licence part" <<'CMD'
bash scripts/verify/T012.sh >/dev/null &&
head -1 LICENSE | grep -qx 'MIT License' && grep -q 'Lucas Menke' LICENSE && test -s third_party/gofont/LICENSE && test -s third_party/misc-fixed/LICENSE
CMD
expect_ok "protected files unchanged; go.mod/go.sum untouched by this task" <<'CMD'
scripts/check-protected.sh && git diff --quiet HEAD -- go.mod go.sum
CMD
expect_fail "negative: font8x8 mentioned, or a file other than the two licences under third_party/" <<'CMD'
test -d third_party || exit 0
grep -rn -i 'font8x8' third_party && exit 0
test "$(find third_party -mindepth 1 -type f | sort | tr '\n' ' ')" != "third_party/gofont/LICENSE third_party/misc-fixed/LICENSE " && { find third_party -type f; exit 0; }
exit 1
CMD
finish
